// SPDX-License-Identifier: LGPL-3.0-only
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.7.0;

interface ISignMessageLib {
    event SignMsg(bytes32 indexed msgHash);

    function getMessageHash(bytes memory message)
        external
        view
        returns (bytes32);

    function signMessage(bytes memory _data) external;
}