// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.7.0;

interface ISignMessageLib {
    function getMessageHash(bytes memory message)
        external
        view
        returns (bytes32);

    function signMessage(bytes memory _data) external;
}