// SPDX-License-Identifier: GPL-3.0+
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.4.24;

interface IDSProxy {
    function setOwner(address owner_) external;

    function execute(address _target, bytes _data)
        external
        payable
        returns (bytes32 response);

    function execute(bytes _code, bytes _data)
        external
        payable
        returns (address target, bytes32 response);

    function cache() external view returns (address);

    function setAuthority(address authority_) external;

    function owner() external view returns (address);

    function setCache(address _cacheAddr) external returns (bool);

    function authority() external view returns (address);

    function() external payable;
    event LogNote(
        bytes4 indexed sig,
        address indexed guy,
        bytes32 indexed foo,
        bytes32 indexed bar,
        uint256 wad,
        bytes fax
    ) anonymous;
    event LogSetAuthority(address indexed authority);
    event LogSetOwner(address indexed owner);
}
