// SPDX-License-Identifier: GPL-3.0+
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.4.24;

interface IProxyRegistry {
    function build() external returns (address proxy);

    function proxies(address) external view returns (address);

    function build(address owner) external returns (address proxy);
}
