// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.8.4;

interface IGasStationExact {
    error DuplicateAddress(address duplicate);
    error InvalidWatchList();
    error OnlyKeeperRegistry();
    error ZeroAddress();
    event ERC20Swept(address indexed token, address payee, uint256 amount);
    event FundsAdded(uint256 amountAdded, uint256 newBalance, address sender);
    event FundsWithdrawn(uint256 amountWithdrawn, address payee);
    event KeeperRegistryAddressUpdated(address oldAddress, address newAddress);
    event MinWaitPeriodUpdated(
        uint256 oldMinWaitPeriod,
        uint256 newMinWaitPeriod
    );
    event OwnershipTransferRequested(address indexed from, address indexed to);
    event OwnershipTransferred(address indexed from, address indexed to);
    event Paused(address account);
    event TopUpFailed(address indexed recipient);
    event TopUpSucceeded(address indexed recipient);
    event Unpaused(address account);

    function acceptOwnership() external;

    function checkUpkeep(bytes memory)
        external
        view
        returns (bool upkeepNeeded, bytes memory performData);

    function getAccountInfo(address targetAddress)
        external
        view
        returns (
            bool isActive,
            uint96 minBalanceWei,
            uint96 minTopUpAmountWei,
            uint56 lastTopUpTimestamp
        );

    function getKeeperRegistryAddress()
        external
        view
        returns (address keeperRegistryAddress);

    function getMinWaitPeriodSeconds() external view returns (uint256);

    function getUnderfundedAddresses() external view returns (address[] memory);

    function getWatchList() external view returns (address[] memory);

    function owner() external view returns (address);

    function pause() external;

    function paused() external view returns (bool);

    function performUpkeep(bytes memory performData) external;

    function setKeeperRegistryAddress(address keeperRegistryAddress) external;

    function setMinWaitPeriodSeconds(uint256 period) external;

    function setWatchList(
        address[] memory addresses,
        uint96[] memory minBalancesWei,
        uint96[] memory topUpAmountsWei
    ) external;

    function sweep(address token, address payee) external;

    function topUpExact(address[] memory needsFunding) external;

    function transferOwnership(address to) external;

    function unpause() external;

    function withdraw(uint256 amount, address payee) external;

    receive() external payable;
}
