// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity ^0.4.24;

interface IMedianOracle {
    function reportDelaySec() external view returns (uint256);

    function pushReport(uint256 payload) external;

    function getData() external returns (uint256, bool);

    function addProvider(address provider) external;

    function providers(uint256) external view returns (address);

    function renounceOwnership() external;

    function removeProvider(address provider) external;

    function owner() external view returns (address);

    function isOwner() external view returns (bool);

    function minimumProviders() external view returns (uint256);

    function purgeReports() external;

    function setReportDelaySec(uint256 reportDelaySec_) external;

    function providersSize() external view returns (uint256);

    function reportExpirationTimeSec() external view returns (uint256);

    function setMinimumProviders(uint256 minimumProviders_) external;

    function providerReports(address, uint256)
        external
        view
        returns (uint256 timestamp, uint256 payload);

    function transferOwnership(address newOwner) external;

    function setReportExpirationTimeSec(uint256 reportExpirationTimeSec_)
        external;

    event ProviderAdded(address provider);
    event ProviderRemoved(address provider);
    event ReportTimestampOutOfRange(address provider);
    event ProviderReportPushed(
        address indexed provider,
        uint256 payload,
        uint256 timestamp
    );
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
}
