// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity ^0.6.0;

interface IBalanceVerifier {
    function verifyBalance(
        address token,
        address holder,
        uint256 minBalance
    ) external;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[{"internalType":"contract IERC20Upgradeable","name":"token","type":"address"},{"internalType":"address","name":"holder","type":"address"},{"internalType":"uint256","name":"minBalance","type":"uint256"}],"name":"verifyBalance","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/
